### ISSUE TITLE
Pro: Setting for opening links in new windows is broken

### ISSUE THREAD

**Issue by MikeNGarrett** [CodeCabin/wp-google-maps#1007]
The setting in your js files, `WPGMZA.settings.wpgmza_settings_infowindow_links`, is looking for the string "yes" instead of the boolean "true" in the following files: 

1. pro-info-window.js
2. pro-marker.js
3. wp-google-maps-pro.combined.js
4. wp-google-maps-pro.min.js

Changing `"yes"` to `true` fixed the issue for me.

**Comment by DylanCodeCabin** [comment]
Thank you for your report. I am sorry this slipped by us! 

The issue should have been resolved from the time it was logged. We are cleaning up this repo in an attempt to reorganize and open a line of communication with reporters. 

As a result, this issue is being closed as `stale` - You can learn more about the future of this repo here:
- https://github.com/CodeCabin/wp-google-maps/issues/1015

Basically, we will be removing all issues, moving relevant items to our internal V9 repo and solving them further there. Once V9 is released to the public, remaining items will be available here if they apply to wide use cases
