### ISSUE TITLE
Marker Listing doesn't show all markers

### ISSUE THREAD

**Issue by Gismo1337** [CodeCabin/wp-google-maps#1013]
Hey,
the Marker Listing in Map and below the Map in Marker Style shows only 21 of 189 items on webpage. in backend it works fine.

Website
![grafik](https://user-images.githubusercontent.com/6397577/122189823-8c0a5800-ce91-11eb-84c8-0161a2b3ab5b.png)

Adminpanel
![grafik](https://user-images.githubusercontent.com/6397577/122189874-975d8380-ce91-11eb-8f41-def1d2bc2dfd.png)

**Comment by DylanCodeCabin** [comment]
Thank you for your report. I am sorry this slipped by us! 

The issue should have been resolved from the time it was logged. We are cleaning up this repo in an attempt to reorganize and open a line of communication with reporters. 

As a result, this issue is being closed as `stale` - You can learn more about the future of this repo here:
- https://github.com/CodeCabin/wp-google-maps/issues/1015

Basically, we will be removing all issues, moving relevant items to our internal V9 repo and solving them further there. Once V9 is released to the public, this repo will become more active with issue tracking and enhancement requests
