### ISSUE TITLE
PRO :: ScriptLoader Dependencies

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#1020]
@DylanCodeCabin

Environment:
PHP Version: 7.4.30
WP Version: 6.0
Build Code: B.9.0.1::P.8.1.20::L.G.D
Internal Engine: Legacy
Map Engine: Google Maps
Developer Mode: Enabled

When WPGM 9.0.1 and Pro 8.1.20 are activated, there are unresolved dependencies that cause the required scripts not to be properly enqueued.

Example.

The `circle.js` (https://github.com/CodeCabin/wp-google-maps/blob/master/js/v8/circle.js) has `@pro-requires WPGMZA.ProShape` in the file header.

This causes the ScriptLoader to register a dependency (https://github.com/CodeCabin/wp-google-maps/blob/master/includes/class.script-loader.php#L225).

This script does not appear to be in WPGM Pro version 8.1.20.

Issue seems to include:

- WPGMZA.ProCircle
- WPGMZA.ProShape
- WPGMZA.ProPointlabel
- WPGMZA.ProRectangle

I submitted this issue because it was stated in the WPGM news that the WPGM 9.0.1 and Pro 8.1.20 combination should work together.

- https://www.wpgmaps.com/wp-google-maps-is-now-wp-go-maps/#comment-73903

**Comment by shazahm1** [comment]
Related #1019

**Comment by DylanCodeCabin** [comment]
@shazahm1 Thank you for the report! Since these came in I updated our readme to explain this exact issue in a bit more detail, and requested any developers to request updated Pro versions from us directly on a case-by-case basis. 

We've spoken via email, and I think you should be all sorted. If not, please do let me know!

Closing this one for now, with the dependency patch going into the consideration list for the next update, although it may be out of the scope for the time being, it would still be a good addition to the compiler system.
