### ISSUE TITLE
Uncaught TypeError: constructor is not a constructor at WPGMZA.CapsuleModules.createInstance

### ISSUE THREAD

**Issue by shazahm1** [CodeCabin/wp-google-maps#1021]
@DylanCodeCabin

Environment:
PHP Version: 7.4.30
WP Version: 6.0
Build Code: B.9.0.1::P.8.1.20::L.G.D
Internal Engine: Legacy
Map Engine: Google Maps
Developer Mode: Enabled

When WPGM 9.0.1 and Pro 8.1.20 are activated.

This error is generated in the browser console:

```
Uncaught TypeError: constructor is not a constructor
    at WPGMZA.CapsuleModules.createInstance (capsule-modules.js?ver=9.0.1+pro-8.1.20:30:10)
    at Object.initCapsules (core.js?ver=9.0.1+pro-8.1.20:771:50)
    at HTMLDocument.<anonymous> (core.js?ver=9.0.1+pro-8.1.20:977:11)
    at mightThrow (jquery.js?ver=3.6.0:3766:29)
    at process (jquery.js?ver=3.6.0:3834:12)
```

This line of code:

``` javascript
	WPGMZA.CapsuleModules.createInstance = function(){
		const constructor = WPGMZA.CapsuleModules.getConstructor();
		return new constructor();
	}
```

**Comment by DylanCodeCabin** [comment]
@shazahm1 Thank you for the report! Since these came in I updated our readme to explain this exact issue in a bit more detail, and requested any developers to request updated Pro versions from us directly on a case-by-case basis. 

We've spoken via email, and I think you should be all sorted. If not, please do let me know!

Closing this one for now, with the dependency patch going into the consideration list for the next update, although it may be out of the scope for the time being, it would still be a good addition to the compiler system.
