### ISSUE TITLE
Plugin conflict with AMP WP (Mobile optimized content)

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#136]
Plugin: https://github.com/Automattic/amp-wp

Issue: Maps don't render on mobile pages when using AMP

**Comment by NickDuncanZA** [comment]
I cannot reproduce this error .Which ticket did this belong to?

**Comment by JarrydLong** [comment]
After installing AMP and adding the map to the page, you need to append /amp to the URL to use the Mobile version of the page - this is when it wouldn't render

**Comment by NickDuncanZA** [comment]
OK confirmed. AMP plugin for WP only supports pages.
When shortcode is on a page and you add "/amp" to the end of the URL, the map is stripped from the page content. Investigating now..

**Comment by NickDuncanZA** [comment]
This is going to be quite tricky... AMP strips out all JS as well as HTML elements (for example, the store locator).

This code gets around the JS issue (keep in mind it's a quick 'hack'):

```
add_action( 'amp_post_template_head' , 'wpgmza_force_amp_js' );
function wpgmza_force_amp_js() {
  if (function_exists('wp_print_scripts')) { 
    wp_print_scripts(array('jquery','wpgmaps_core'));
  }
}
```

The challenge to overcome the HTML elements still exists. An idea was to modify the HTML of the store locator prior to it going through the AMP sanitizer so that the sanitizer doesnt recognize the elements, then normalize the HTML once the sanitize function has ended. there are filters before and after the sanitizer that we could make use of.

**Comment by DylanCodeCabin** [comment]
After looking into this further we have found that AMP focuses on rendering static pages, and as such rendering things like form inputs is not supported at the moment. 

As such we have decided to wait until this is supported in AMP by default. For this reason we will not be adding the hook seen above. 

Please see the Proof Of Concept Statement below:
`AMP HTML is a way to build web pages for static content that render with reliable, fast performance." ` - https://github.com/ampproject/amphtml

October 7 Announcement: 
`We decided to focus entirely on static content as it lends itself to more radical optimization approaches that are easier to apply across the board.` - https://www.ampproject.org/how-it-works/

It appears Google is not focusing on this at the moment, and as such we will not be developing any functionality which defeats the objective of using AMP.
