### ISSUE TITLE
All localized data needs to be passed in arrays

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#548]
Otherwise a warning will be issued in PHP >= 7.1

**Comment by NickDuncanZA** [comment]
What is the warning?

**Comment by andtrev** [comment]
This would be the warning we're seeing in wplc as well. Basically if you pass in an empty string you get $string[0] = ''; which now causes a warning in PHP 7.1+. The localize script functionality expects an array and acts on data as if it were an array regardless of what you pass in.

**Comment by NickDuncanZA** [comment]
wp_localize_script is a standard WP function that I dont want to get away from at this point. We just need to be more strict with the data we insert into that function

**Comment by PerryRylance** [comment]
We can still use it but passing scalar values will issue warnings in several places in PHP 7.1

**Comment by NickDuncanZA** [comment]
Noted, but we shouldnt be parsing scalar values anyway. We use "1" (string) for true in this instance to do any checks.

**Comment by andtrev** [comment]
Maybe we should create a helper function to check the values before calling wp_localize_script, then just bulk replace all the wp_localize_script calls so we're sure not to pass in empty strings or scalar values?

It is a standard WP function, but we're using it in a non-standard way, which could be an issue in the future even more so since we could get unexpected results, like with these warnings. It expects, and really demands, an array of strings as that's what the underlying code is built to operate on.
