### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#684]
Reported by NYU

**Images - visitor**

Marker icons in directions section do not have ALT tags

**Keyboard navigation - visitor**

When the actual map is focused for keyboard panning using the arrow keys, it is not highlighted (no outline).

**Input fields - visitor**

Fields for entering To and From Directions lack labels.

**Color - content creator**

- Existing maps popup - the following elements have insufficient contrast:
- - existing maps shortcode
- On New map options popup, the following elements have insufficient contrast:
- - legends on fieldsets
- - associate map description
- - global defaults description

**Headings - content creator**

Existing maps popup - suggest "Existing maps" title is a heading

On New map options popup, suggest "New Map" title is a heading

**Images - content creator**

On the "New Map" page, the map does not appear to have a TITLE attribute (in lieu of an ALT tag as it is a dynamic image rather than a static image).

On New map options popup, the justification buttons seem to lack alternative text.

**Keyboard navigation - content creator**

On the Existing maps screen, the options that appear when the mouse hovers over an existing map cannot be made visible using the keyboard.

**Input Fields - content creator**

On New map options popup, the map size fields appear to lack labels.

**Comment by PerryRylance** [comment]
> Marker icons in directions section do not have ALT tags

We don't control this - this HTML comes directly from Google. It doesn't appear that they provide any events that we can listen for in order to detect when the list has been updated and add these.

> When the actual map is focused for keyboard panning using the arrow keys, it is not highlighted (no outline).

Unfortunately it appears there is no means for us to detect when the map has keyboard focus.

> Fields for entering To and From Directions lack labels.

This has been addressed in Pro 7 and 8.

> Existing maps popup - the following elements have insufficient contrast:
> existing maps shortcode

We've overhauled the entire interface in WP Google Maps 8, this is now high contrast.

> On New map options popup, the following elements have insufficient contrast:

> legends on fieldsets

We don't presently use legends or fieldsets, could this be different software?

> associate map description
> global defaults description

We don't support map description or global descriptions.

> On the "New Map" page, the map does not appear to have a TITLE attribute (in lieu of an ALT tag as it is a dynamic image rather than a static image).

We have no control over the JavaScript engines HTML elements, it's not something we'd write a workaround for as it would be considered bad practise for us to attempt to manipulate the Google Maps JavaScript engine HTML. I'd suggest bringing this up in the relevant Google Groups. We've done this in the past and unfortunately haven't had a response on that point.

> On the Existing maps screen, the options that appear when the mouse hovers over an existing map cannot be made visible using the keyboard.

Again, I'm very sorry, but this is something that would have to be taken up with Google.

> On New map options popup, the map size fields appear to lack labels.

We've had labels here as far back as version 6.
