### ISSUE TITLE
wpgmaps-admin-core.js is not enqueued

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-google-maps#748]
The symptom of this is bulk marker controls not working

**Comment by PerryRylance** [comment]
- Check it's not actually being enqueued
- Identify where it should be enqueued
- Work backwards from there to find out why (I imagine a dependency issue)

**Comment by PerryRylance** [comment]
Couldn't reproduce, wpgmaps-admin-core.js is enqueued

**Comment by garrett-eclipse** [comment]
Hi @PerryRylance thanks for the investigation.

Looking into this further I found the issue is due to gold/pro being in place. With them in place the `wpgmaps_admin_javascript_basic` is never called. Instead `wpgmaps_admin_javascript_gold` or `wpgmaps_admin_javascript_pro` are called. Neither of which contain the enqueue to the `wpgmaps-admin-core.js` file. I'm not sure if that's on purpose, if it is then most likely the select/delete bulk actions just need to be replicated in those other enqueues or have javascript required for basic features always enqueued.

Hope that helps reproduce the issue.
Cheers
